#!/bin/bash
KAAZING_JMS_GATEWAY=kaazing-websocket-gateway-jms-4.0.5
ACTIVEMQ=apache-activemq-5.5.1
KAAZING_JMS_GATEWAY_JAR=$KAAZING_JMS_GATEWAY.tar.gz
KAAZING_JMS_GATEWAY_URL=http://kaazingcorp.cachefly.net/com/download/jms/4.0.5.359/$KAAZING_JMS_GATEWAY.tar.gz

echo "******* build script from DIY cartridge ..." >> ${OPENSHIFT_DIY_LOG_DIR}/build.log 2>&1 
date >> ${OPENSHIFT_DIY_LOG_DIR}/build.log 2>&1
echo "KAAZING_JMS_GATEWAY_JAR: $KAAZING_JMS_GATEWAY_JAR" >> ${OPENSHIFT_DIY_LOG_DIR}/build.log 2>&1 
echo "KAAZING_JMS_GATEWAY_URL: $KAAZING_JMS_GATEWAY_URL" >> ${OPENSHIFT_DIY_LOG_DIR}/build.log 2>&1 

set -x 

cd $OPENSHIFT_DATA_DIR

if [ ! -e "$KAAZING_JMS_GATEWAY_JAR" ]; then
	echo "Downloading Kaazing Gateway..." >> ${OPENSHIFT_DIY_LOG_DIR}/build.log 2>&1 
	wget $KAAZING_JMS_GATEWAY_URL -O $KAAZING_JMS_GATEWAY_JAR

	tar xzf $KAAZING_JMS_GATEWAY_JAR | tee -a ${OPENSHIFT_DIY_LOG_DIR}/build.log 2>&1 

	echo "Patching the files with $OPENSHIFT_DIY_IP ..." >> ${OPENSHIFT_DIY_LOG_DIR}/build.log 2>&1 
	sed -i "s/0.0.0.0/$OPENSHIFT_DIY_IP/g" $ACTIVEMQ/conf/*.xml

	sed -i "94 a\
        <property name=\"host\" value=\"$OPENSHIFT_DIY_IP\" />" $ACTIVEMQ/conf/jetty.xml

	sed -i "s/localhost/$OPENSHIFT_DIY_IP/g" $KAAZING_JMS_GATEWAY/conf/*.xml
	sed -i "s/8000/16000/g" $KAAZING_JMS_GATEWAY/conf/*.xml
	sed -i "s/8001/16001/g" $KAAZING_JMS_GATEWAY/conf/*.xml
    echo "Patching done." >> ${OPENSHIFT_DIY_LOG_DIR}/build.log 2>&1 
fi

cd $OPENSHIFT_DATA_DIR

# Start ActiveMQ
date >> ${OPENSHIFT_DIY_LOG_DIR}/start.log 2>&1
echo "Starting ActiveMQ ..." >> ${OPENSHIFT_DIY_LOG_DIR}/start.log 2>&1 
nohup java -jar apache-activemq-5.5.1/bin/run.jar start > $OPENSHIFT_DIY_LOG_DIR/activemq-server.log 2>&1 &
echo "ActiveMQ done." >> ${OPENSHIFT_DIY_LOG_DIR}/start.log 2>&1 

# Start Kaazing JMS Gateway
date >> ${OPENSHIFT_DIY_LOG_DIR}/start.log 2>&1
echo "Starting Kaazing Gateway ..." >> ${OPENSHIFT_DIY_LOG_DIR}/start.log 2>&1 
nohup ./kaazing-websocket-gateway-jms-4.0.5/bin/gateway.start > $OPENSHIFT_DIY_LOG_DIR/kaazing-gateway.log 2>&1 &
echo "Kaazing Gateway done." >> ${OPENSHIFT_DIY_LOG_DIR}/start.log 2>&1 

